import {useEffect,useState} from 'react';
import {Alert,Box,Button,Divider,CircularProgress,Paper,Stack,TextField,Typography} from '@mui/material';
import {getCompatibility,login,restoreAuth,bootstrapAdmin,AuthContext} from '../api/client';
import {isClientCompatible} from '../runtime/clientShell';

type State={kind:'loading'}|{kind:'login';error?:string;notice?:string}|{kind:'ready';auth:AuthContext}|{kind:'blocked';message:string};
export function AuthGate({children}:{children:React.ReactNode}){
  const [state,setState]=useState<State>({kind:'loading'}); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [mfa,setMfa]=useState(''); const [bootstrapToken,setBootstrapToken]=useState('');
  useEffect(()=>{(async()=>{try{const c=await getCompatibility();if(!isClientCompatible(c)){setState({kind:'blocked',message:'Frontend/backend API sürümleri uyumsuz. Risk artırıcı işlemler bloklandı.'});return}try{const auth=await restoreAuth();setState({kind:'ready',auth})}catch{setState({kind:'login'})}}catch{setState({kind:'blocked',message:'Sunucu compatibility kontrolü yapılamadı. İşlem yapılmayacak.'})}})()},[]);
  if(state.kind==='loading')return <Box p={4}><CircularProgress aria-label="Oturum kontrol ediliyor"/></Box>;
  if(state.kind==='blocked')return <Box p={4}><Alert severity="error">{state.message}</Alert></Box>;
  if(state.kind==='login')return <Box sx={{minHeight:'100vh',display:'grid',placeItems:'center',p:2}}><Paper sx={{p:3,width:'min(460px,100%)'}}><Stack spacing={2}><Typography variant="h5">Güvenli Giriş</Typography><Alert severity="info">İlk kurulum ve trading ekranları authenticated session gerektirir.</Alert>{state.notice&&<Alert severity="success">{state.notice}</Alert>}{state.error&&<Alert id="login-error" severity="error">{state.error}</Alert>}<TextField label="Kullanıcı adı" error={Boolean(state.error)} helperText={state.error?"Kullanıcı adı/parola/MFA bilgilerini kontrol edin.":undefined} aria-describedby="login-error" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/><TextField label="Parola" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/><TextField label="MFA kodu (aktifse)" value={mfa} onChange={e=>setMfa(e.target.value)} inputProps={{inputMode:'numeric'}}/><Button variant="contained" onClick={async()=>{try{const auth=await login(username,password,mfa||undefined);setState({kind:'ready',auth})}catch{setState({kind:'login',error:'Giriş doğrulanamadı.'})}}}>Giriş yap</Button><Divider>İlk kurulum</Divider><Typography variant="body2" color="text.secondary">Sunucuda henüz kullanıcı yoksa install sırasında oluşturulan tek kullanımlık bootstrap token ile ilk admin hesabını oluşturabilirsiniz. Token kaydedilmez.</Typography><TextField label="Bootstrap token" type="password" value={bootstrapToken} onChange={e=>setBootstrapToken(e.target.value)} autoComplete="off"/><Button variant="outlined" onClick={async()=>{try{await bootstrapAdmin(username,password,bootstrapToken);setBootstrapToken('');setState({kind:'login',notice:'Admin hesabı oluşturuldu. Şimdi giriş yapın.'})}catch{setState({kind:'login',error:'Admin bootstrap işlemi reddedildi.'})}}}>İlk admin hesabını oluştur</Button></Stack></Paper></Box>;
  return <>{children}</>
}
