import {Alert,Box,Card,CardContent,Chip,Stack,Table,TableBody,TableCell,TableHead,TableRow,Typography,useMediaQuery,useTheme} from '@mui/material';

type Candidate={symbol:string;signal:string;score:number;confidence:string;regime:string;netEdge:string;blockReason:string};
const demo:Candidate[]=[{symbol:'BTCUSDT',signal:'NO_TRADE',score:72,confidence:'Orta',regime:'BULLISH_TREND',netEdge:'0.18%',blockReason:'Canlı veri snapshotı bekleniyor'}];

function CandidateCard({row}:{row:Candidate}){return <Card variant="outlined"><CardContent><Stack spacing={1}><Stack direction="row" justifyContent="space-between"><Typography variant="h6">{row.symbol}</Typography><Chip label={row.signal}/></Stack><Typography>Skor: {row.score} · Confidence: {row.confidence}</Typography><Typography>Rejim: {row.regime}</Typography><Typography>Net Edge: {row.netEdge}</Typography><Typography color="text.secondary">Risk/Block Nedeni: {row.blockReason}</Typography></Stack></CardContent></Card>}

export default function Scanner(){
 const theme=useTheme(); const mobile=useMediaQuery(theme.breakpoints.down('sm'));
 return <Stack spacing={2}><Typography variant="h4">Piyasa / Coin Tarayıcı</Typography><Alert severity="info">Sadece point-in-time uygunluk, likidite, spread, depth, history ve veri kalitesi kapılarından geçen semboller aday olur.</Alert><Typography>Scanner sonucu backend source-of-truth’tur. Yeni listelemeler karantina politikasına tabidir.</Typography><Card variant="outlined"><CardContent><Stack spacing={0.5}><Typography variant="h6">Universe / Risk Özeti</Typography><Typography>Aktif Universe: point-in-time eligible symbols</Typography><Typography>Hariç bırakılma gerekçeleri: stale, spread, volume, depth, listing age, suspension/delisting</Typography><Typography>Likidite / Spread / Volume filtre durumu: backend eligibility sonucu</Typography><Typography>Korelasyon matrisi / cluster-tema konsantrasyonu / quote-asset exposure: portföy risk görünümü</Typography><Typography>Per-symbol data health ve new-listing risk badge görünürdür.</Typography></Stack></CardContent></Card>{mobile?<Stack spacing={1} aria-label="Scanner kart görünümü">{demo.map(row=><CandidateCard key={row.symbol} row={row}/>)}</Stack>:<Box sx={{overflowX:'auto'}}><Table size="small" aria-label="Scanner tablo görünümü"><TableHead><TableRow>{['Sembol','Sinyal','Skor','Confidence','Rejim','Net Edge','Risk/Block Nedeni'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{demo.map(row=><TableRow key={row.symbol}><TableCell>{row.symbol}</TableCell><TableCell>{row.signal}</TableCell><TableCell>{row.score}</TableCell><TableCell>{row.confidence}</TableCell><TableCell>{row.regime}</TableCell><TableCell>{row.netEdge}</TableCell><TableCell>{row.blockReason}</TableCell></TableRow>)}</TableBody></Table></Box>}</Stack>
}
