param(
    [string]$RepoUrl = "https://github.com/erdincbostan1827/Kripto.git",
    [string]$BundlePath = (Join-Path $PSScriptRoot "crypto_trading_platform_v5_1_phase220_git.bundle"),
    [string]$ReferencePath = (Join-Path $PSScriptRoot "PHASE221_EXACT_REFERENCE.json"),
    [string]$ResultPath = (Join-Path $PSScriptRoot "PHASE221_NATIVE_IMPORT_RESULT.json")
)
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
function Fail([string]$Message){ throw $Message }
function Run-Git { param([Parameter(Mandatory=$true)][string[]]$Args,[string]$WorkingDirectory=""); if($WorkingDirectory){$o=& git -C $WorkingDirectory @Args 2>&1}else{$o=& git @Args 2>&1}; if($LASTEXITCODE -ne 0){Fail ("git "+($Args -join " ")+" failed:`n"+($o -join "`n"))}; return @($o) }
function Git-Line { param([string[]]$Args,[string]$WorkingDirectory); $o=Run-Git -Args $Args -WorkingDirectory $WorkingDirectory; if($o.Count -eq 0){return ""}; return [string]$o[0] }
function Split-Shas([string]$Text){ if([string]::IsNullOrWhiteSpace($Text)){return @()}; return @($Text.Trim() -split "\s+") }
function Assert-Seq { param([object[]]$Expected,[object[]]$Actual,[string]$Label); if($Expected.Count -ne $Actual.Count){Fail "$Label count mismatch expected=$($Expected.Count) actual=$($Actual.Count)"}; for($i=0;$i -lt $Expected.Count;$i++){if([string]$Expected[$i] -ne [string]$Actual[$i]){Fail "$Label mismatch index=$i expected=$($Expected[$i]) actual=$($Actual[$i])"}} }
function Validate-Graph { param([string]$RepoPath,$Reference,[string]$HeadRef="refs/heads/candidate"); $head=Git-Line @("rev-parse",$HeadRef) $RepoPath; if($head -ne $Reference.canonical_candidate_sha){Fail "HEAD mismatch expected=$($Reference.canonical_candidate_sha) actual=$head"}; $count=[int](Git-Line @("rev-list","--count",$HeadRef) $RepoPath); if($count -ne [int]$Reference.commit_count){Fail "commit count mismatch"}; foreach($c in $Reference.commits){Run-Git @("cat-file","-e","$($c.sha)^{commit}") $RepoPath|Out-Null; $tree=Git-Line @("show","-s","--format=%T",$c.sha) $RepoPath; if($tree -ne $c.tree_sha){Fail "tree mismatch $($c.sha)"}; $ap=Split-Shas (Git-Line @("show","-s","--format=%P",$c.sha) $RepoPath); Assert-Seq @($c.parents) $ap "parents $($c.sha)"}; $graph=@(Run-Git @("rev-list","--topo-order","--reverse",$HeadRef) $RepoPath); $set=@{}; foreach($c in $Reference.commits){$set[$c.sha]=$true}; if($graph.Count -ne [int]$Reference.commit_count){Fail "graph count mismatch"}; foreach($sha in $graph){if(-not $set.ContainsKey([string]$sha)){Fail "unexpected commit $sha"}}; foreach($t in $Reference.annotated_tags){$r="refs/tags/$($t.name)"; if((Git-Line @("cat-file","-t",$r) $RepoPath) -ne "tag"){Fail "tag not annotated $($t.name)"}; if((Git-Line @("rev-parse",$r) $RepoPath) -ne $t.tag_object_sha){Fail "tag object mismatch $($t.name)"}; if((Git-Line @("rev-parse","$r^{}") $RepoPath) -ne $t.target_sha){Fail "tag target mismatch $($t.name)"}}; return $head }
if(-not(Get-Command git -ErrorAction SilentlyContinue)){Fail "Git is not installed/on PATH"}
if(-not(Test-Path -LiteralPath $BundlePath -PathType Leaf)){Fail "Bundle not found: $BundlePath"}
if(-not(Test-Path -LiteralPath $ReferencePath -PathType Leaf)){Fail "Reference not found: $ReferencePath"}
$r=Get-Content $ReferencePath -Raw|ConvertFrom-Json; $canonical=[string]$r.canonical_candidate_sha; $sha=(Get-FileHash $BundlePath -Algorithm SHA256).Hash.ToLowerInvariant(); if($sha -ne ([string]$r.bundle_sha256).ToLowerInvariant()){Fail "bundle SHA mismatch"}; if((Get-Item $BundlePath).Length -ne [int64]$r.bundle_size){Fail "bundle size mismatch"}
$tmp=Join-Path ([IO.Path]::GetTempPath()) ("phase221-native-import-"+[guid]::NewGuid().ToString("N")); $local=Join-Path $tmp "local.git"; $verify=Join-Path $tmp "remote-verify.git"; New-Item -ItemType Directory $tmp|Out-Null
$result=[ordered]@{phase=221;started_utc=(Get-Date).ToUniversalTime().ToString("o");repo_url=$RepoUrl;bundle_sha256=$sha;canonical_candidate_sha=$canonical;remote_main_before=$null;remote_main_after=$null;backup_branch=$null;atomic_push_executed=$false;graph_verified_after_push=$false;status="FAIL";error=$null}
try{
 Run-Git @("init","--bare",$local)|Out-Null; Run-Git @("bundle","verify",(Resolve-Path $BundlePath).Path) $local|Out-Null; $sb=[string]$r.source_branch_in_bundle; Run-Git @("fetch","--no-tags",(Resolve-Path $BundlePath).Path,"refs/heads/${sb}:refs/heads/candidate") $local|Out-Null; Run-Git @("fetch",(Resolve-Path $BundlePath).Path,"+refs/tags/*:refs/tags/*") $local|Out-Null; Validate-Graph $local $r|Out-Null; Run-Git @("remote","add","origin",$RepoUrl) $local|Out-Null
 $ml=@(Run-Git @("ls-remote","--refs","origin","refs/heads/main") $local); if($ml.Count -ne 1){Fail "remote main must exist exactly once"}; $before=(($ml[0]-split "\s+")[0]).Trim(); $result.remote_main_before=$before
 foreach($t in $r.annotated_tags){$tr="refs/tags/$($t.name)"; $e=@(Run-Git @("ls-remote","--refs","origin",$tr) $local); if($e.Count -gt 1){Fail "remote tag duplicate $($t.name)"}; if($e.Count -eq 1){$es=(($e[0]-split "\s+")[0]).Trim(); if($es -ne $t.tag_object_sha){Fail "conflicting remote tag $($t.name)"}}}
 if($before -ne $canonical){Run-Git @("fetch","--no-tags","origin","refs/heads/main:refs/remotes/origin/bootstrap-main") $local|Out-Null; $backup="phase221-pre-exact-history-"+(Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ"); $result.backup_branch=$backup; $a=@("push","--atomic","--force-with-lease=refs/heads/main:$before","origin","refs/remotes/origin/bootstrap-main:refs/heads/$backup","refs/heads/candidate:refs/heads/main"); foreach($t in $r.annotated_tags){$a+="refs/tags/$($t.name):refs/tags/$($t.name)"}; Run-Git $a $local|Out-Null; $result.atomic_push_executed=$true }
 $ma=@(Run-Git @("ls-remote","--refs","origin","refs/heads/main") $local); if($ma.Count -ne 1){Fail "remote main missing after push"}; $after=(($ma[0]-split "\s+")[0]).Trim(); $result.remote_main_after=$after; if($after -ne $canonical){Fail "remote main exact closure failed expected=$canonical actual=$after"}
 Run-Git @("init","--bare",$verify)|Out-Null; Run-Git @("remote","add","origin",$RepoUrl) $verify|Out-Null; Run-Git @("fetch","--no-tags","origin","refs/heads/main:refs/heads/candidate") $verify|Out-Null; Run-Git @("fetch","origin","+refs/tags/*:refs/tags/*") $verify|Out-Null; Validate-Graph $verify $r|Out-Null; $result.graph_verified_after_push=$true; $result.status="PASS"; $result.finished_utc=(Get-Date).ToUniversalTime().ToString("o"); $result|ConvertTo-Json -Depth 6|Set-Content $ResultPath -Encoding UTF8; Write-Host "PHASE221_EXACT_HISTORY_CLOSURE=PASS"; Write-Host "GitHub main=$canonical"; exit 0
}catch{$result.error=$_.Exception.Message;$result.finished_utc=(Get-Date).ToUniversalTime().ToString("o");try{$result|ConvertTo-Json -Depth 6|Set-Content $ResultPath -Encoding UTF8}catch{};Write-Error $_.Exception.Message;exit 1}finally{Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue}
