from __future__ import annotations
from datetime import datetime
from sqlalchemy import String,Text,DateTime,Boolean,Integer,Numeric,JSON,ForeignKey,UniqueConstraint,func
from sqlalchemy.orm import DeclarativeBase,Mapped,mapped_column
class Base(DeclarativeBase):
    """Declarative base for financial persistence models."""
class User(Base):
    __tablename__='users'; id:Mapped[str]=mapped_column(String(32),primary_key=True); username:Mapped[str]=mapped_column(String(120),unique=True,index=True); password_hash:Mapped[str]=mapped_column(Text); role:Mapped[str]=mapped_column(String(20)); mfa_enabled:Mapped[bool]=mapped_column(Boolean,default=False); mfa_secret_encrypted:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ExchangeAccount(Base):
    __tablename__='exchange_accounts'; id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange:Mapped[str]=mapped_column(String(40),index=True); account_fingerprint:Mapped[str]=mapped_column(String(128),index=True); market_type:Mapped[str]=mapped_column(String(20)); capabilities:Mapped[dict]=mapped_column(JSON,default=dict); permission_snapshot:Mapped[dict]=mapped_column(JSON,default=dict); status:Mapped[str]=mapped_column(String(40),default='ACTIVE'); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ApiCredential(Base):
    __tablename__='api_credentials'; id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id',ondelete='CASCADE')); key_fingerprint:Mapped[str]=mapped_column(String(128)); encrypted_api_key:Mapped[str]=mapped_column(Text); encrypted_secret:Mapped[str]=mapped_column(Text); permission_snapshot:Mapped[dict]=mapped_column(JSON,default=dict)
class Order(Base):
    __tablename__='orders'; __table_args__=(UniqueConstraint('exchange_account_id','exchange_order_id',name='uq_exchange_order'),UniqueConstraint('intent_id',name='uq_intent'),); id:Mapped[str]=mapped_column(String(32),primary_key=True); intent_id:Mapped[str]=mapped_column(String(64)); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id')); symbol:Mapped[str]=mapped_column(String(50),index=True); side:Mapped[str]=mapped_column(String(8)); order_type:Mapped[str]=mapped_column(String(32)); quantity:Mapped[object]=mapped_column(Numeric(38,18)); price:Mapped[object|None]=mapped_column(Numeric(38,18),nullable=True); stop_price:Mapped[object|None]=mapped_column(Numeric(38,18),nullable=True); status:Mapped[str]=mapped_column(String(32)); exchange_order_id:Mapped[str|None]=mapped_column(String(80),nullable=True); client_order_id:Mapped[str]=mapped_column(String(80)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Fill(Base):
    __tablename__='fills'; __table_args__=(UniqueConstraint('exchange_account_id','trade_id',name='uq_exchange_trade'),); id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id')); order_id:Mapped[str]=mapped_column(ForeignKey('orders.id')); trade_id:Mapped[str]=mapped_column(String(80)); quantity:Mapped[object]=mapped_column(Numeric(38,18)); price:Mapped[object]=mapped_column(Numeric(38,18)); fee_asset:Mapped[str|None]=mapped_column(String(32),nullable=True); fee_amount:Mapped[object]=mapped_column(Numeric(38,18),default=0)
class Position(Base):
    __tablename__='positions'; __table_args__=(UniqueConstraint('exchange_account_id','symbol',name='uq_account_position'),); id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id')); symbol:Mapped[str]=mapped_column(String(50)); quantity:Mapped[object]=mapped_column(Numeric(38,18)); average_entry:Mapped[object]=mapped_column(Numeric(38,18)); realized_pnl:Mapped[object]=mapped_column(Numeric(38,18),default=0)
class AccountBalance(Base):
    __tablename__='account_balances'; __table_args__=(UniqueConstraint('exchange_account_id','asset',name='uq_account_balance'),); id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id')); asset:Mapped[str]=mapped_column(String(32)); free:Mapped[object]=mapped_column(Numeric(38,18)); locked:Mapped[object]=mapped_column(Numeric(38,18)); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class DomainEventRow(Base):
    __tablename__='domain_events'; event_id:Mapped[str]=mapped_column(String(32),primary_key=True); event_type:Mapped[str]=mapped_column(String(80),index=True); schema_version:Mapped[int]=mapped_column(Integer); aggregate_id:Mapped[str]=mapped_column(String(80),index=True); correlation_id:Mapped[str]=mapped_column(String(64)); sequence:Mapped[int]=mapped_column(Integer); event_time:Mapped[datetime]=mapped_column(DateTime(timezone=True)); received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); producer_version:Mapped[str]=mapped_column(String(40)); payload_hash:Mapped[str]=mapped_column(String(64)); payload:Mapped[dict]=mapped_column(JSON)
class OutboxEvent(Base):
    __tablename__='outbox_events'; id:Mapped[str]=mapped_column(String(32),primary_key=True); event_id:Mapped[str]=mapped_column(String(32),unique=True); topic:Mapped[str]=mapped_column(String(80)); payload:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); attempts:Mapped[int]=mapped_column(Integer,default=0); next_attempt_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); last_error:Mapped[str|None]=mapped_column(Text,nullable=True)
class DeadLetterRow(Base):
    __tablename__='dead_letters'; id:Mapped[str]=mapped_column(String(32),primary_key=True); original_event_id:Mapped[str]=mapped_column(String(32),unique=True); event_type:Mapped[str]=mapped_column(String(80)); schema_version:Mapped[int]=mapped_column(Integer); payload_hash:Mapped[str]=mapped_column(String(64)); failure_reason:Mapped[str]=mapped_column(Text); correlation_id:Mapped[str]=mapped_column(String(64)); attempts:Mapped[int]=mapped_column(Integer); consumer_version:Mapped[str]=mapped_column(String(40),default='unknown'); first_failed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); last_failed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); resolution_state:Mapped[str]=mapped_column(String(20),default='OPEN')
class AuditLog(Base):
    __tablename__='audit_log'; id:Mapped[str]=mapped_column(String(32),primary_key=True); previous_hash:Mapped[str]=mapped_column(String(64)); current_hash:Mapped[str]=mapped_column(String(64),unique=True); actor:Mapped[str]=mapped_column(String(120)); action:Mapped[str]=mapped_column(String(80)); object_ref:Mapped[str]=mapped_column(String(160)); correlation_id:Mapped[str]=mapped_column(String(64),index=True); reason:Mapped[str]=mapped_column(Text); release_version:Mapped[str]=mapped_column(String(40)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class SessionRow(Base):
    __tablename__='sessions'; id:Mapped[str]=mapped_column(String(64),primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); token_hash:Mapped[str]=mapped_column(String(64),unique=True); csrf_hash:Mapped[str]=mapped_column(String(64)); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class MfaRecoveryCode(Base):
    __tablename__='mfa_recovery_codes'; id:Mapped[str]=mapped_column(String(32),primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); code_hash:Mapped[str]=mapped_column(String(64),unique=True); used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class PasswordResetToken(Base):
    __tablename__='password_reset_tokens'; id:Mapped[str]=mapped_column(String(32),primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); token_hash:Mapped[str]=mapped_column(String(64),unique=True); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class SignalRow(Base):
    __tablename__='signals'; id:Mapped[str]=mapped_column(String(32),primary_key=True); symbol:Mapped[str]=mapped_column(String(50),index=True); signal:Mapped[str]=mapped_column(String(24)); score:Mapped[int]=mapped_column(Integer); confidence:Mapped[object]=mapped_column(Numeric(12,8)); regime:Mapped[str]=mapped_column(String(40)); data_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True)); signal_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True)); universe_snapshot_id:Mapped[str|None]=mapped_column(String(32),nullable=True); fingerprint:Mapped[str]=mapped_column(String(64),unique=True); explainability:Mapped[dict]=mapped_column(JSON)
class SignalFeature(Base):
    __tablename__='signal_features'; id:Mapped[str]=mapped_column(String(32),primary_key=True); signal_id:Mapped[str]=mapped_column(ForeignKey('signals.id',ondelete='CASCADE'),index=True); feature_name:Mapped[str]=mapped_column(String(80)); value:Mapped[object|None]=mapped_column(Numeric(38,18),nullable=True); payload:Mapped[dict]=mapped_column(JSON,default=dict)
class SignalOutcome(Base):
    __tablename__='signal_outcomes'; id:Mapped[str]=mapped_column(String(32),primary_key=True); signal_id:Mapped[str]=mapped_column(ForeignKey('signals.id',ondelete='CASCADE'),unique=True); outcome:Mapped[str]=mapped_column(String(32)); return_value:Mapped[object]=mapped_column(Numeric(38,18)); mfe:Mapped[object]=mapped_column(Numeric(38,18)); mae:Mapped[object]=mapped_column(Numeric(38,18)); time_to_tp_seconds:Mapped[int|None]=mapped_column(Integer,nullable=True); time_to_sl_seconds:Mapped[int|None]=mapped_column(Integer,nullable=True)
class Strategy(Base):
    __tablename__='strategies'; id:Mapped[str]=mapped_column(String(32),primary_key=True); name:Mapped[str]=mapped_column(String(80)); version:Mapped[str]=mapped_column(String(40)); lifecycle_state:Mapped[str]=mapped_column(String(32)); specification:Mapped[dict]=mapped_column(JSON); config_hash:Mapped[str]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class StrategyRun(Base):
    __tablename__='strategy_runs'; id:Mapped[str]=mapped_column(String(32),primary_key=True); strategy_id:Mapped[str]=mapped_column(ForeignKey('strategies.id')); mode:Mapped[str]=mapped_column(String(20)); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); ended_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); metrics:Mapped[dict]=mapped_column(JSON,default=dict)
class StrategyLotRow(Base):
    __tablename__='strategy_lots'; id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id')); strategy_id:Mapped[str]=mapped_column(String(80),index=True); symbol:Mapped[str]=mapped_column(String(50),index=True); quantity:Mapped[object]=mapped_column(Numeric(38,18)); cost_basis:Mapped[object]=mapped_column(Numeric(38,18)); realized_pnl:Mapped[object]=mapped_column(Numeric(38,18),default=0); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class LedgerEntry(Base):
    __tablename__='ledger_entries'; id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id'),index=True); event_type:Mapped[str]=mapped_column(String(40)); asset:Mapped[str]=mapped_column(String(32)); amount:Mapped[object]=mapped_column(Numeric(38,18)); reference_type:Mapped[str]=mapped_column(String(40)); reference_id:Mapped[str]=mapped_column(String(64)); event_time:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
class PortfolioSnapshot(Base):
    __tablename__='portfolio_snapshots'; id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id'),index=True); snapshot_time:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); equity:Mapped[object]=mapped_column(Numeric(38,18)); cash:Mapped[object]=mapped_column(Numeric(38,18)); gross_exposure:Mapped[object]=mapped_column(Numeric(38,18)); drawdown:Mapped[object]=mapped_column(Numeric(18,10)); payload:Mapped[dict]=mapped_column(JSON,default=dict)
class RiskEvent(Base):
    __tablename__='risk_events'; id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str|None]=mapped_column(ForeignKey('exchange_accounts.id'),nullable=True); severity:Mapped[str]=mapped_column(String(20)); risk_state:Mapped[str]=mapped_column(String(32)); reason:Mapped[str]=mapped_column(Text); payload:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True)
class Alert(Base):
    __tablename__='alerts'; id:Mapped[str]=mapped_column(String(32),primary_key=True); alert_type:Mapped[str]=mapped_column(String(40)); severity:Mapped[str]=mapped_column(String(20)); symbol:Mapped[str|None]=mapped_column(String(50),nullable=True); message:Mapped[str]=mapped_column(Text); delivery_state:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Backtest(Base):
    __tablename__='backtests'; id:Mapped[str]=mapped_column(String(32),primary_key=True); strategy_id:Mapped[str]=mapped_column(String(80)); dataset_hash:Mapped[str]=mapped_column(String(64)); config_hash:Mapped[str]=mapped_column(String(64)); universe_snapshot_ref:Mapped[str|None]=mapped_column(String(64),nullable=True); metrics:Mapped[dict]=mapped_column(JSON); status:Mapped[str]=mapped_column(String(20)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class BacktestTrade(Base):
    __tablename__='backtest_trades'; id:Mapped[str]=mapped_column(String(32),primary_key=True); backtest_id:Mapped[str]=mapped_column(ForeignKey('backtests.id',ondelete='CASCADE'),index=True); symbol:Mapped[str]=mapped_column(String(50)); entry_time:Mapped[datetime]=mapped_column(DateTime(timezone=True)); exit_time:Mapped[datetime]=mapped_column(DateTime(timezone=True)); quantity:Mapped[object]=mapped_column(Numeric(38,18)); entry_price:Mapped[object]=mapped_column(Numeric(38,18)); exit_price:Mapped[object]=mapped_column(Numeric(38,18)); pnl:Mapped[object]=mapped_column(Numeric(38,18)); costs:Mapped[dict]=mapped_column(JSON)
class WalkForwardRun(Base):
    __tablename__='walk_forward_runs'; id:Mapped[str]=mapped_column(String(32),primary_key=True); backtest_id:Mapped[str|None]=mapped_column(ForeignKey('backtests.id'),nullable=True); train_window:Mapped[dict]=mapped_column(JSON); test_window:Mapped[dict]=mapped_column(JSON); metrics:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class MonteCarloRun(Base):
    __tablename__='monte_carlo_runs'; id:Mapped[str]=mapped_column(String(32),primary_key=True); backtest_id:Mapped[str|None]=mapped_column(ForeignKey('backtests.id'),nullable=True); simulations:Mapped[int]=mapped_column(Integer); seed:Mapped[int]=mapped_column(Integer); metrics:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ResearchTrial(Base):
    __tablename__='research_trials'; id:Mapped[str]=mapped_column(String(32),primary_key=True); strategy_version:Mapped[str]=mapped_column(String(80)); universe_version:Mapped[str]=mapped_column(String(80)); parameter_space:Mapped[dict]=mapped_column(JSON); feature_set:Mapped[dict]=mapped_column(JSON); timeframe_set:Mapped[dict]=mapped_column(JSON); train_window:Mapped[dict]=mapped_column(JSON); oos_window:Mapped[dict]=mapped_column(JSON); primary_metric:Mapped[str]=mapped_column(String(40)); outcome:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class SystemEvent(Base):
    __tablename__='system_events'; id:Mapped[str]=mapped_column(String(32),primary_key=True); event_type:Mapped[str]=mapped_column(String(80),index=True); severity:Mapped[str]=mapped_column(String(20)); correlation_id:Mapped[str]=mapped_column(String(64),index=True); payload:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class HealthCheck(Base):
    __tablename__='health_checks'; id:Mapped[str]=mapped_column(String(32),primary_key=True); component:Mapped[str]=mapped_column(String(80)); status:Mapped[str]=mapped_column(String(24)); latency_ms:Mapped[object|None]=mapped_column(Numeric(18,6),nullable=True); details:Mapped[dict]=mapped_column(JSON,default=dict); checked_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True)
class AssetMaster(Base):
    __tablename__='asset_master'; id:Mapped[str]=mapped_column(String(64),primary_key=True); canonical_symbol:Mapped[str]=mapped_column(String(32),index=True); display_name:Mapped[str]=mapped_column(String(120)); metadata_source:Mapped[str]=mapped_column(String(80)); metadata_version:Mapped[int]=mapped_column(Integer); active_from:Mapped[datetime]=mapped_column(DateTime(timezone=True)); active_to:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); extra:Mapped[dict]=mapped_column(JSON,default=dict)
class SymbolMaster(Base):
    __tablename__='symbol_master'; id:Mapped[str]=mapped_column(String(64),primary_key=True); exchange:Mapped[str]=mapped_column(String(40)); market_type:Mapped[str]=mapped_column(String(20)); symbol:Mapped[str]=mapped_column(String(50),index=True); base_asset_id:Mapped[str]=mapped_column(ForeignKey('asset_master.id')); quote_asset_id:Mapped[str]=mapped_column(ForeignKey('asset_master.id')); status:Mapped[str]=mapped_column(String(24)); valid_from:Mapped[datetime]=mapped_column(DateTime(timezone=True)); valid_to:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); filters:Mapped[dict]=mapped_column(JSON)
class SymbolMetadataVersion(Base):
    __tablename__='symbol_metadata_versions'; id:Mapped[str]=mapped_column(String(32),primary_key=True); symbol_master_id:Mapped[str]=mapped_column(ForeignKey('symbol_master.id',ondelete='CASCADE'),index=True); version:Mapped[int]=mapped_column(Integer); valid_from:Mapped[datetime]=mapped_column(DateTime(timezone=True)); valid_to:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); payload:Mapped[dict]=mapped_column(JSON); source:Mapped[str]=mapped_column(String(80))
class UniverseSnapshotRow(Base):
    __tablename__='universe_snapshots'; id:Mapped[str]=mapped_column(String(32),primary_key=True); snapshot_time:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); rules_hash:Mapped[str]=mapped_column(String(64)); eligible_count:Mapped[int]=mapped_column(Integer)
class UniverseMembership(Base):
    __tablename__='universe_memberships'; id:Mapped[str]=mapped_column(String(32),primary_key=True); snapshot_id:Mapped[str]=mapped_column(ForeignKey('universe_snapshots.id',ondelete='CASCADE'),index=True); symbol:Mapped[str]=mapped_column(String(50)); eligible:Mapped[bool]=mapped_column(Boolean); exclusion_reasons:Mapped[dict]=mapped_column(JSON,default=dict)
class ListingEvent(Base):
    __tablename__='listing_events'; id:Mapped[str]=mapped_column(String(32),primary_key=True); symbol:Mapped[str]=mapped_column(String(50),index=True); effective_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); source:Mapped[str]=mapped_column(String(80)); payload:Mapped[dict]=mapped_column(JSON)
class DelistingEvent(Base):
    __tablename__='delisting_events'; id:Mapped[str]=mapped_column(String(32),primary_key=True); symbol:Mapped[str]=mapped_column(String(50),index=True); effective_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); source:Mapped[str]=mapped_column(String(80)); payload:Mapped[dict]=mapped_column(JSON)
class AssetRiskProfile(Base):
    __tablename__='asset_risk_profiles'; id:Mapped[str]=mapped_column(String(32),primary_key=True); symbol:Mapped[str]=mapped_column(String(50),index=True); risk_class:Mapped[str]=mapped_column(String(40)); valid_from:Mapped[datetime]=mapped_column(DateTime(timezone=True)); valid_to:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); limits:Mapped[dict]=mapped_column(JSON)
class LiquiditySnapshot(Base):
    __tablename__='liquidity_snapshots'; id:Mapped[str]=mapped_column(String(32),primary_key=True); symbol:Mapped[str]=mapped_column(String(50),index=True); snapshot_time:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); spread_bps:Mapped[object]=mapped_column(Numeric(18,8)); depth_notional:Mapped[object]=mapped_column(Numeric(38,18)); quote_volume_24h:Mapped[object]=mapped_column(Numeric(38,18))
class CorrelationSnapshot(Base):
    __tablename__='correlation_snapshots'; id:Mapped[str]=mapped_column(String(32),primary_key=True); snapshot_time:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); window:Mapped[str]=mapped_column(String(24)); matrix:Mapped[dict]=mapped_column(JSON)
class PortfolioRiskSnapshot(Base):
    __tablename__='portfolio_risk_snapshots'; id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id')); snapshot_time:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); metrics:Mapped[dict]=mapped_column(JSON); risk_state:Mapped[str]=mapped_column(String(32))
class ScannerRun(Base):
    __tablename__='scanner_runs'; id:Mapped[str]=mapped_column(String(32),primary_key=True); universe_snapshot_id:Mapped[str]=mapped_column(ForeignKey('universe_snapshots.id')); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); config_hash:Mapped[str]=mapped_column(String(64)); status:Mapped[str]=mapped_column(String(20))
class ScannerCandidate(Base):
    __tablename__='scanner_candidates'; id:Mapped[str]=mapped_column(String(32),primary_key=True); scanner_run_id:Mapped[str]=mapped_column(ForeignKey('scanner_runs.id',ondelete='CASCADE'),index=True); symbol:Mapped[str]=mapped_column(String(50)); rank:Mapped[int]=mapped_column(Integer); score:Mapped[object]=mapped_column(Numeric(18,8)); confidence:Mapped[object]=mapped_column(Numeric(18,8)); net_edge_bps:Mapped[object]=mapped_column(Numeric(18,8)); blocked:Mapped[bool]=mapped_column(Boolean); reasons:Mapped[dict]=mapped_column(JSON)
class AllocationDecision(Base):
    __tablename__='allocation_decisions'; id:Mapped[str]=mapped_column(String(32),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id')); scanner_run_id:Mapped[str|None]=mapped_column(ForeignKey('scanner_runs.id'),nullable=True); symbol:Mapped[str]=mapped_column(String(50)); strategy_id:Mapped[str]=mapped_column(String(80)); reserved_capital:Mapped[object]=mapped_column(Numeric(38,18)); risk_budget:Mapped[object]=mapped_column(Numeric(38,18)); decision:Mapped[str]=mapped_column(String(24)); reason:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Incident(Base):
    __tablename__='incidents'; id:Mapped[str]=mapped_column(String(32),primary_key=True); severity:Mapped[str]=mapped_column(String(12)); detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); affected_scope:Mapped[str]=mapped_column(String(160)); automatic_action:Mapped[str]=mapped_column(String(80)); risk_state:Mapped[str]=mapped_column(String(32)); correlation_ids:Mapped[dict]=mapped_column(JSON); operator_actions:Mapped[dict]=mapped_column(JSON,default=dict); resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); recovery_validation:Mapped[dict]=mapped_column(JSON,default=dict)
class LeaderLease(Base):
    __tablename__='leader_leases'; account_id:Mapped[str]=mapped_column(String(32),primary_key=True); instance_id:Mapped[str]=mapped_column(String(80)); fencing_token:Mapped[int]=mapped_column(Integer); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class CapitalReservationRow(Base):
    __tablename__='capital_reservations'; intent_id:Mapped[str]=mapped_column(String(64),primary_key=True); exchange_account_id:Mapped[str]=mapped_column(ForeignKey('exchange_accounts.id'),index=True); amount:Mapped[object]=mapped_column(Numeric(38,18)); asset:Mapped[str]=mapped_column(String(32)); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); released_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class SetupState(Base):
    __tablename__='setup_state'; id:Mapped[str]=mapped_column(String(32),primary_key=True); user_id:Mapped[str|None]=mapped_column(ForeignKey('users.id'),nullable=True); current_step:Mapped[int]=mapped_column(Integer); completed_steps:Mapped[dict]=mapped_column(JSON); non_secret_config:Mapped[dict]=mapped_column(JSON); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
