from enum import StrEnum

class TradingMode(StrEnum):
    BACKTEST="BACKTEST"; PAPER="PAPER"; TESTNET="TESTNET"; LIVE="LIVE"; LIVE_SHADOW="LIVE_SHADOW"
class MarketType(StrEnum): SPOT="SPOT"; PERPETUAL="PERPETUAL"
class Environment(StrEnum): DEV="DEV"; TEST="TEST"; STAGING="STAGING"; PROD="PROD"
class RiskState(StrEnum): STARTING="STARTING"; PAPER_ONLY="PAPER_ONLY"; ACTIVE="ACTIVE"; NORMAL="NORMAL"; DEGRADED="DEGRADED"; RESTRICTED="RESTRICTED"; REDUCING_ONLY="REDUCING_ONLY"; HALTED="HALTED"; RECOVERY_PENDING="RECOVERY_PENDING"; MANUAL_REVIEW_REQUIRED="MANUAL_REVIEW_REQUIRED"; STOPPING="STOPPING"
class OrderState(StrEnum): CREATED="CREATED"; SUBMITTED="SUBMITTED"; ACKNOWLEDGED="ACKNOWLEDGED"; PARTIALLY_FILLED="PARTIALLY_FILLED"; FILLED="FILLED"; CANCEL_PENDING="CANCEL_PENDING"; CANCELLED="CANCELLED"; REJECTED="REJECTED"; FAILED="FAILED"; UNKNOWN="UNKNOWN"
class Signal(StrEnum): STRONG_BUY="STRONG_BUY"; BUY="BUY"; WATCH="WATCH"; HOLD="HOLD"; REDUCE="REDUCE"; SELL="SELL"; STRONG_SELL="STRONG_SELL"; NO_TRADE="NO_TRADE"
